### ISSUE TITLE
Deployment via Docker

### ISSUE THREAD

**Issue by moqmar** [manuel-uberti/boodle#10]
When reading the prerequisites, this application requires to set up and understand a lot of stuff. Would it be possible to provide a Docker image? That way, this could be run easily with just one command (`docker-compose up -d`) and a docker-compose.yml:

```yaml
version: "3"
services:
  app:
    image: manuel-ubert/boodle
    restart: unless-stopped
    volumes: ["./config.edn:/data/conf/config.edn"]
    ports: ["8080:8080"]
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: boodle
```

I can create a pull request with a Dockerfile if you'd like to add Docker support, then you only need to add an automated build on https://cloud.docker.com.
